apiVersion: v1
kind: Secret
metadata:
  name: anon-key-auth
  labels:
    konghq.com/credential: key-auth
stringData:
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
---
apiVersion: v1
kind: Secret
metadata:
  name: anon-acl
  labels:
    konghq.com/credential: acl
stringData:
  group: anon