apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase
namePrefix: supabase-

resources:
  - db.yaml
  - auth.yaml
  - rest.yaml
  - realtime.yaml
  - studio.yaml
  #- analytics.yaml
  - imgproxy.yaml
  - meta.yaml
  - functions.yaml
  - supavisor.yaml
  #- kong-plugins.yaml
  - kong-routes.yaml
  - storage.yaml
  #- vector.yaml

configMapGenerator:
  # - name: common-config
  #   env: .env
  - name: postgres-init-scripts
    files:
      - 97-_supabase.sql=volumes/db/custom-init-scripts/_supabase.sql
      - 98-webhooks.sql=volumes/db/custom-init-scripts/webhooks.sql
      - 99-jwt.sql=volumes/db/custom-init-scripts/jwt.sql
      - 99-roles.sql=volumes/db/custom-init-scripts/roles.sql
      - 99-realtime.sql=volumes/db/custom-init-scripts/realtime.sql
      - 99-logs.sql=volumes/db/custom-init-scripts/logs.sql
      - 99-pooler.sql=volumes/db/custom-init-scripts/pooler.sql
  - name: postgres-migration-scripts
    files:
      - volumes/db/custom-migrations/20250528154547_init_mon_leo.sql
  - name: edge-functions-config
    files:
      - volumes/edge-functions/functions.tar
  - name: pooler-config
    files:
      - volumes/pooler/pooler.exs
      - volumes/pooler/runtime.exs
  - name: vector-config
    files:
      - volumes/vector/vector.yml
      
  # - name: vector-config
  #   files:
  #     - volumes/vector/vector.yml
  

# secretGenerator:
#   - name: common-secrets
#     env: .env.secrets

# Configuration des images utilis√©es
images:
  - name: supabase/postgres
    newName: supabase/postgres
    newTag: 15.8.1.060
  - name: supabase/gotrue
    newName: supabase/gotrue
    newTag: v2.172.1
  - name: postgrest/postgrest
    newName: postgrest/postgrest
    newTag: v12.2.12
  - name: supabase/realtime
    newName: supabase/realtime
    newTag: v2.34.47
  - name: supabase/studio
    newName: supabase/studio
    newTag: 2025.05.19-sha-3487831
  - name: supabase/logflare
    newName: supabase/logflare
    newTag: 1.12.0
  - name: darthsim/imgproxy
    newName: darthsim/imgproxy
    newTag: v3.8.0
  - name: supabase/postgres-meta
    newName: supabase/postgres-meta
    newTag: v0.89.0
  - name: supabase/edge-runtime
    newName: supabase/edge-runtime
    newTag: v1.67.4
  - name: supabase/supavisor
    newName: supabase/supavisor
    newTag: 2.5.1
  - name: timberio/vector
    newName: timberio/vector
    newTag: 0.47.0-alpine