apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.konghq.com
      targetRevision: "0.20.0"
      chart: ingress
      # helm:
      #   valueFiles:
      #     - $values/k8s/apps/kong/overlays/dev/values.yaml
    # - repoURL: https://github.com/Isipharm/kubernetes-supabase-test.git
    #   targetRevision: main
    #   ref: values
    - repoURL: https://github.com/Isipharm/kubernetes-supabase-test.git
      targetRevision: main
      path: k8s/apps/kong
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase